#!/bin/bash

GFS_STAGED_FG=2
GFS_NOT_STAGED_FG=1
GFS_UNTRACKED_FG=3
GFS_IGNORED_FG=240

GFS_STAGED_TITLE="Staged"
GFS_NOT_STAGED_TITLE="Not staged"
GFS_UNTRACKED_TITLE="Untracked"
GFS_IGNORED_TITLE="Ignored"

GFS_MODIFIED_TEXT="modified"
GFS_ADDED_TEXT="new file"
GFS_DELETED_TEXT="deleted"
GFS_RENAMED_TEXT="renamed"
GFS_COPIED_TEXT="copied"

function print_files() {
	local status="$1"
	shift
	local files=("$@")

	[ "$status" != "" ] && status="$status:   "

	for file in "${files[@]}"; do
		echo -e "\t$status$file"
	done
}

modified_idx=()
modified_wrk=()

added_idx=()
added_wrk=()

deleted_idx=()
deleted_wrk=()

renamed_idx=()
renamed_wrk=()

copied_idx=()
copied_wrk=()

unmerged_idx=()
unmerged_wrk=()

untracked=();ignored=()

while IFS= read -r line; do
	idx=${line:0:1}
	wrk=${line:1:1}
	file=${line:3}

	[ "$idx" = "M" ] && modified_idx+=($file)
	[ "$idx" = "A" ] && added_idx+=($file)
	[ "$idx" = "D" ] && deleted_idx+=($file)
	[ "$idx" = "R" ] && renamed_idx+=($file)
	[ "$idx" = "C" ] && copied_idx+=($file)
	[ "$idx" = "U" ] && unmerged_idx+=($file)

	[ "$wrk" = "M" ] && modified_wrk+=($file)
	[ "$wrk" = "A" ] && added_wrk+=($file)
	[ "$wrk" = "D" ] && deleted_wrk+=($file)
	[ "$wrk" = "R" ] && renamed_wrk+=($file)
	[ "$wrk" = "C" ] && copied_wrk+=($file)
	[ "$wrk" = "U" ] && unmerged_wrk+=($file)

	[ "$idx" = "?" ] && untracked+=($file)
	[ "$idx" = "!" ] && ignored+=($file)
done

idx_count=$((${#modified_idx[@]}+${#added_idx[@]}+${#deleted_idx[@]}+${#renamed_idx[@]}+${#copied_idx[@]}+${#unmerged_idx[@]}))
if [ "$idx_count" -gt 0 ]; then
	tput setaf $GFS_STAGED_FG
	echo "$GFS_STAGED_TITLE ($idx_count)"
	print_files "$GFS_MODIFIED_TEXT" "${modified_idx[@]}"
	print_files "$GFS_ADDED_TEXT" "${added_idx[@]}"
	print_files "$GFS_DELETED_TEXT" "${deleted_idx[@]}"
	print_files "$GFS_RENAMED_TEXT" "${renamed_idx[@]}"
	print_files "$GFS_COPIED_TEXT" "${copied_idx[@]}"
	tput sgr0
fi

wrk_count=$((${#modified_wrk[@]}+${#added_wrk[@]}+${#deleted_wrk[@]}+${#renamed_wrk[@]}+${#copied_wrk[@]}+${#unmerged_wrk[@]}))
if [ "$wrk_count" -gt 0 ]; then
	tput setaf $GFS_NOT_STAGED_FG
	echo "$GFS_NOT_STAGED_TITLE ($wrk_count)"
	print_files "$GFS_ADDED_TEXT" "${added_wrk[@]}"
	print_files "$GFS_MODIFIED_TEXT" "${modified_wrk[@]}"
	print_files "$GFS_DELETED_TEXT" "${deleted_wrk[@]}"
	print_files "$GFS_RENAMED_TEXT" "${renamed_wrk[@]}"
	print_files "$GFS_COPIED_TEXT" "${copied_wrk[@]}"
	tput sgr0
fi

untracked_count="${#untracked[@]}"
if [ "$untracked_count" -gt 0 ]; then
	tput setaf $GFS_UNTRACKED_FG
	echo "$GFS_UNTRACKED_TITLE ($untracked_count)"
	print_files "" "${untracked[@]}"
	tput sgr0
fi

ignored_count="${#ignored[@]}"
if [ "$ignored_count" -gt 0 ]; then
	tput setaf $GFS_IGNORED_FG
	echo "$GFS_IGNORED_TITLE ($ignored_count)"
	print_files "" "${ignored[@]}"
	tput sgr0
fi
