#!/bin/bash

# helper functions
function config() {
	local name="$1"
	local default="$2"
	local value=$(git config "fancy-status.$name")
	[ -z "$value" ] && value=$default
	echo $value
}

function print_files() {
	local status="$1"
	shift
	local files=("$@")

	[ "$status" != "" ] && status="$status:   "

	for file in "${files[@]}"; do
  	echo -e " $status$file"
	done
}

# configuration variables
STAGED_FG=$(config "stageFg" "2")
NOT_STAGED_FG=$(config "notStagedFg" "1")
UNTRACKED_FG=$(config "untrackedFg" "3")
IGNORED_FG=$(config "ignoredFg" "240")

STAGED_TITLE=$(config "stagedTitle" "staged")
NOT_STAGED_TITLE=$(config "notStagedTitle" "not staged")
UNTRACKED_TITLE=$(config "untrackedTitle" "untracked")
IGNORED_TITLE=$(config "ignoredTitle" "ignored")

MODIFIED_TEXT=$(config "modifiedText" "modified")
ADDED_TEXT=$(config "addedText" "new file")
DELETED_TEXT=$(config "deletedText" "deleted")
RENAMED_TEXT=$(config "renamedText" "renamed")
COPIED_TEXT=$(config "copiedText" "copied")

modified_idx=()
modified_wrk=()

added_idx=()
added_wrk=()

deleted_idx=()
deleted_wrk=()

renamed_idx=()
renamed_wrk=()

copied_idx=()
copied_wrk=()

unmerged_idx=()
unmerged_wrk=()

untracked=();ignored=()

while IFS= read -r line; do
	idx=${line:0:1}
	wrk=${line:1:1}
	file=${line:3}

	[ "$idx" = "M" ] && modified_idx+=("$file")
	[ "$idx" = "A" ] && added_idx+=("$file")
	[ "$idx" = "D" ] && deleted_idx+=("$file")
	[ "$idx" = "R" ] && renamed_idx+=("$file")
	[ "$idx" = "C" ] && copied_idx+=("$file")
	[ "$idx" = "U" ] && unmerged_idx+=("$file")

	[ "$wrk" = "M" ] && modified_wrk+=("$file")
	[ "$wrk" = "A" ] && added_wrk+=("$file")
	[ "$wrk" = "D" ] && deleted_wrk+=("$file")
	[ "$wrk" = "R" ] && renamed_wrk+=("$file")
	[ "$wrk" = "C" ] && copied_wrk+=("$file")
	[ "$wrk" = "U" ] && unmerged_wrk+=("$file")

	[ "$idx" = "?" ] && untracked+=("$file")
	[ "$idx" = "!" ] && ignored+=("$file")
done < <(git status "$@" --porcelain)

idx_count=$((${#modified_idx[@]}+${#added_idx[@]}+${#deleted_idx[@]}+${#renamed_idx[@]}+${#copied_idx[@]}+${#unmerged_idx[@]}))
if [ "$idx_count" -gt 0 ]; then
	tput setaf $STAGED_FG
	echo "$STAGED_TITLE ($idx_count)"
	print_files "$MODIFIED_TEXT" "${modified_idx[@]}"
	print_files "$ADDED_TEXT" "${added_idx[@]}"
	print_files "$DELETED_TEXT" "${deleted_idx[@]}"
	print_files "$RENAMED_TEXT" "${renamed_idx[@]}"
	print_files "$COPIED_TEXT" "${copied_idx[@]}"
	tput sgr0
fi

wrk_count=$((${#modified_wrk[@]}+${#added_wrk[@]}+${#deleted_wrk[@]}+${#renamed_wrk[@]}+${#copied_wrk[@]}+${#unmerged_wrk[@]}))
if [ "$wrk_count" -gt 0 ]; then
	tput setaf $NOT_STAGED_FG
	echo "$NOT_STAGED_TITLE ($wrk_count)"
	print_files "$ADDED_TEXT" "${added_wrk[@]}"
	print_files "$MODIFIED_TEXT" "${modified_wrk[@]}"
	print_files "$DELETED_TEXT" "${deleted_wrk[@]}"
	print_files "$RENAMED_TEXT" "${renamed_wrk[@]}"
	print_files "$COPIED_TEXT" "${copied_wrk[@]}"
	tput sgr0
fi

untracked_count="${#untracked[@]}"
if [ "$untracked_count" -gt 0 ]; then
	tput setaf $UNTRACKED_FG
	echo "$UNTRACKED_TITLE ($untracked_count)"
	print_files "" "${untracked[@]}"
	tput sgr0
fi

ignored_count="${#ignored[@]}"
if [ "$ignored_count" -gt 0 ]; then
	tput setaf $IGNORED_FG
	echo "$IGNORED_TITLE ($ignored_count)"
	print_files "" "${ignored[@]}"
	tput sgr0
fi
